### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by vinod1147** [free-icons/free-icons#10]
I have forked the repo and installed in my local machine, but when I load the website I can only see the navbar and the loading animation

**Comment by free-icons** [comment]
If you want to run it in your local machine you should run `npm i && npm run build && npm run test` and open the `dist/index.html` file in your browser

Additionally, If you want to collaborate you may not want to rebuild it every time (it takes a long time), I prefer you to copy the dist/data.json file to the root of the project and now you can open the index.html found at the root of the project, make any changes and see it instantly
