### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by vinod1147** [free-icons/free-icons#28]
Can you add a button to switch the theme from white to dark?

**Comment by a-rustacean** [comment]
Thank you for the excellent suggestion. I'll certainly prioritize it. As an individual, I have numerous responsibilities, which can limit my ability to communicate frequently. Consequently, the progress on free-icons development is moving at a slower pace. I would greatly appreciate contributions from the open-source community.

**Comment by vinod1147** [comment]
Alright, no worries I tried doing that I was able to add the toggle button it changed the background of the page but I was not able to change the colour of the box. As a beginner, I was not able to find a solution, but still trying...

**Comment by a-rustacean** [comment]
I'm genuinely delighted to see your dedicated efforts to enhance your support for Free Icons. In line with this commitment, I'm planning to initiate a new and comprehensive discussion within the community. The primary focus of this discussion will be to gather valuable insights and opinions from our community members regarding the possibility of transitioning to a tech stack that is not only more reliable but also significantly easier to maintain. Your input and feedback will be instrumental in guiding our decision-making process, ensuring that we make the best choice to benefit our community as a whole.
